GET http://localhost:3000/

###

GET http://localhost:3000/task


###

POST http://localhost:3000/task
content-type: application/json

{
    "title": "task3",
    "description": "x"
}


### 

POST http://localhost:3000/task
content-type: application/json

{
    "title": "taskwithdesc",
}



###

DELETE http://localhost:3000/task/68173d6be39e31ff2fd2769e


###
PATCH  http://localhost:3000/task/68173e2297a271db6c18caf0
content-type: application/json

{
    "title": "new task3"
}